# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 730cb615e82d7050e7a5593313b0268e705eb0b9369868aa7c064110356ddc1e0e51f2021ab03652b40e05d05a096d78d1b864a801d285c3945a80f8da044569

test:
  secret_key_base: 5480174298e9a896c3eb162c5b2d0c395caa533dfd24284abe3c27ba2c8052bba95520f14aa63e9b9d1fd011dbdb2c23f5111b9bab381627ac457f984395cb34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
